### ISSUE TITLE
誤字発見

### ISSUE THREAD

**Issue by a-kashiwagi** [OTL/ros_book_programs#1]
P.182 L.7 誤：「そこに「ROS」の側をかぶせることで」　→　正：「皮（がわ）」？

**Comment by OTL** [comment]
ありがとうございます。その通りです。

正誤表アップデートしました。

https://github.com/OTL/ros_book_programs/wiki/%E6%9C%AC%E3%81%AE%E6%AD%A3%E8%AA%A4%E8%A1%A8
