### ISSUE TITLE
正誤表の間違い

### ISSUE THREAD

**Issue by robograffitti** [OTL/ros_book_programs#2]
正誤表のアップデートお願いします。
https://github.com/OTL/ros_book_programs/wiki/%E6%9C%AC%E3%81%AE%E6%AD%A3%E8%AA%A4%E8%A1%A8

以下が正しいのではないでしょうか？
P29: 中段 rqt_graph -> rostopic echo /turtle1/cmd_vel

**Comment by robograffitti** [comment]
追加です。
P.72: 中段「パラメータ」を取得しているのは以下の2行です。
sub = rospy.Subscriber('/mobile_base/events/bumper', BumperEvent, callback)

以下が正しいと思われます。
vel_x = rospy.get_param('~vel_x', 0.5)
vel_rot = rospy.get_param('~vel_z', 1.0)

**Comment by OTL** [comment]
ありがとうございます!!

確認して追記しました。
