### ISSUE TITLE
p174 について

### ISSUE THREAD

**Issue by RyodoTanaka** [OTL/ros_book_programs#3]
p174 `tf_echo`によりフレーム間の相対位置を調べる箇所
#### 元

``` bash
$ rosrun tf tf_echo /head_plate_frame /l_gripper_leframe
```
#### 修正

``` bash
$ rosrun tf tf_echo /head_plate_frame /l_gripper_led_frame
```

と思われます。
コンソール表記下の説明部分も同様にフレーム名に誤りがあると考えられます。

よろしくお願いします。

**Comment by OTL** [comment]
ありがとうございます。更新しました！

led_frameは今タイプしても間違ってしまいました。。。
