### ISSUE TITLE
些細な脱字を見つけました。

### ISSUE THREAD

**Issue by a-kashiwagi** [OTL/ros_book_programs#5]
些細な脱字を見つけましたので、ご連絡しておきます。
次版用チェックリストにでも入れてください。

P.14
　2.3 「Twitter」について

　誤：　…「つぶや」かれることあるので…　→正(恐らく)：…「つぶや」かれることがあるので…

宜しくお願い致します。

**Comment by OTL** [comment]
確認しました。ありがとうございます！wiki更新しておきました。
